### ISSUE TITLE
Access to some objects in rhel 8

### ISSUE THREAD

**Issue by garnier-quentin** [rhinstaller/hello-world-anaconda-addon#23]
Hi,

In rhel7, i could do add some packages at the beginning of installation process in file: ```ks/myaddon.py``` and that method:
```
class MyaddonData(AddonData):
...
   def setup(self, storage, ksdata, instclass, payload):
        ksdata.packages.packageList.extend(['test'])
```

In last version of anaconda, it's not used anymore and we need to use ```configure_with_tasks```. But in that method, i don't access to payload or ksdata objects (in method paramater). How can i do to manipulate packages selection in that method ?
I have done it in my spoke. But the software selection spoke can reset it.

**Comment by poncovka** [comment]
Hello!

Unfortunately, the DBus support for the payload installation is very limited in RHEL 8 and there is no API that would allow to modify the packages selection. However, you should be able to use your implementation for RHEL 7 with some minor changes. We support both solutions at this moment.

In upstream, it is possible to declare package and group requirements of your add-on with `collect_requirements`:

```
    def collect_requirements(self):
        """Return installation requirements.

        :return: a list of requirements
        """
        requirements = []

        if self.kdump_enabled:
            requirements.append(
                Requirement.for_package(
                    package_name="kexec-tools",
                    reason="Required by kdump add-on."
                )
            )

        return requirements
```

This support will be available in the next RHEL. It will be also possible to modify the packages selection directly.

**Comment by jkonecny12** [comment]
Thanks @poncovka for the explanation!

Closing this issue based on https://github.com/rhinstaller/hello-world-anaconda-addon/issues/23#issuecomment-737777271. If you need further assistance we can definitely re-open this issue.
