### ISSUE TITLE
Wanted: More detailed deployment instructions

### ISSUE THREAD

**Issue by StefanSchroeder** [rhinstaller/hello-world-anaconda-addon#8]
Hi

I am trying to get the hello-world anaconda-addon to work. I have created the CPIO image and I am sending it via http. The kernel-cmdline includes inst.updates=http:/192.168.X.X/update.img.
The kickstart file (that is also supplied via http) contains 
%addon org_fedora_hello_world
Random Text
%end

But still, it doesn't do anything! (Meaning: it doesn't show up in the anaconda GUI).
What am I supposed to see? Why does glade crash when I open the ui file?
Any hint is appreciated.
I studied http://rhinstaller.github.io/anaconda-addon-development-guide/index.html
but to no avail.

**Comment by poncovka** [comment]
Hello,
here are more detailed instructions:

Create an identical directory structure somewhere on your system, for example:
`$ mkdir -p ~/temp/usr/share/anaconda/addons/` 

Place a copy of your add-on's package into it:
`$ cp -r org_fedora_hello_world ~/temp/usr/share/anaconda/addons/` 

Change the current directory to your temporary one:
`$ cd ~/temp`

Check the future content of your updates image with a command:
```
$ find .
.
./usr
./usr/share
./usr/share/anaconda
./usr/share/anaconda/addons
./usr/share/anaconda/addons/org_fedora_hello_world
...
```

And create your updates image with the following command:
`$ find . | cpio -c -o | gzip -9 > addon_updates.img`

In the installation environment, you can check the location of your addon with:
```
$ find / -name org_fedora_hello_world
/usr/share/anaconda/addons/org_fedora_hello_world
```

**Comment by poncovka** [comment]
In the summary hub, you should see:

![loaded_addon](https://user-images.githubusercontent.com/7396092/29275534-bdc3773c-810b-11e7-9e20-223e627712f0.png)

**Comment by StefanSchroeder** [comment]
Nice, thank you.
